#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \setCJKmainfont{Microsoft YaHei}
#+OPTIONS: \n:t
#+TITLE:  0415 团建情况搜集

* 李鹏
** 基本情况
+ 入职日期 2014/7/28
+  毕业时间：2008年7月
毕业学校：吉林大学
最高学历：本科
专业：通信工程
+  家庭情况
目前家里5口人，父母+配偶+4岁小孩
目前住在 吉大的君怡花园， 已经在拱北买了房子， 山水华庭
妻子之前在广州一家事业单位工作， 后来去了华发做规划，现在去了横琴发改委做产业研究
** 毕业后工作经历
11月/2009年-至今        盟讯(广州)电子有限公司                                       广州
系统软件工程师  副课长
工作职责：
+ 2014年作为G3/G4，智能Pager，基于NO#2平台开发系统软件负责人；
+ 2013年承担Remote Watch，智能手表项目软件负责人，配合公司特殊产品使用，基于NO#1-平台开发进行开发，具体工作内容包括：和硬件人员一起，进行关键器件的选型，包括CPU、电子墨水LCD、触摸屏、蓝牙模块等；工作计划制定、工作安排、产出物Review；整体软件架构的定义，本设备和其它蓝牙设备之间的通信协议的制定
+ 2013年AMBE，低码率语音编解码算法项目负责人，完成核心部分的定点算法及优化，兼任DSP课一组组长，负责公司DSP team的建立；
+ 2012年台湾中研院地震预防系统，基于U3项目 的 负责人在地震发生后的3秒内，通过Radio系统，发布出去，以减少伤亡，涉及蓝牙等Linux技术；
+2012年承担NO#3，公司高端平台，使用Ti公司OMAP4440（Cortex A9）芯片，运行Linux及Android  及Minicell，短距离无线通信产品项目中软件负责人的角色，该项目基于NO#1平台开发；预研类工作，查阅各种短距离无线通信技术，选出可行方案，最终在蓝牙、WIFI、Radio、802.15.4等方案中，选中802.15.4方案，目前该系列产品正成为公司主力研发的产品；
+ 2011年期间担任蓝牙类产品，蓝牙产品为公司配件类产品软件负责人，主要使用CSR公司的BC04和BC05芯片NO #1，公司低端平台，使用ST公司STM32F1/F4（Cortex M3/M4）芯片，运行Porting自开源软件的实时操作系统（RTOS）NO #2，公司中端平台，使用三星公司S3C2451（ARM9）芯片，运行嵌入式Linux系统
+ 2010年期间作为主力开发人员参与NO#2，公司中端平台，使用三星公司S3C2451（ARM9）芯片，运行嵌入式Linux系统；并且参作为开发人员与U3，Radio产品，使用ADI的ARM9+DSP双核处理器，运行嵌入式Linux操作系统的开发；
+ 2009年参与开发的项目为TDCIS，可以连接并交换公司所有无线产品的PBX，包括PSTN、GSM、Radio、Pager、Internet：具体负责USB PSTN语音卡firmware的设计与实现，USB GSM语音卡firmware的实现，Linux PBX驱动（DAHDI）的开发，Linux PBX软件（Asterisk）的移植和维护。

07月/2008年-11月/2009年        青岛海信移动技术有限公司
驱动软件工程师
工作职责：
            C2810/C2813，高通平台下的手机产品，负责高通平台驱动软件的开发，包括NAND Flash、SDRAM、Camera、LCD等模块。

** 面试情况
一面：侯景昆（通过）
    晚上电话和李鹏聊了一下，情况如下：
+ 目前已经离职一个多月，主要是觉得前公司的管理风格有些不合适，希望出来看看其他公司是如何研发的；
+ 目前工作六年左右，薪水13K/月＋年终2个月奖金，自认为是比较低的了，难以接受更低的薪酬；
+ 表达能力还不错，描述技术内容的时候话还比较多；
+ 有做过usb、wifi和蓝牙的经验，应该还是比较适合我们这边的；
+ usb能说出枚举的过程，各种传输类型，问到包大小的时候有些答不上来；wifi部分有移植使用的经验，但是不深入，不了解有supplicant的存在，说不出wifi驱动提供给应用层的接口方式，也没有说出端对端的组网过程，这个可能和他们产品使用场景非常简单有关；
+ 蓝牙部分似乎了解得多些，目前他们使用的是bluez协议栈，也知道BT2.0,3.0,4.0的一些差异；
+ 本科毕业于吉林大学，学校还不错；

 综合来看，还是比较适合我们这边，也还有培养潜力。建议约来二面。

二面： 侯景昆，张东风
+ 先聊了一下蓝牙相关，蓝牙这块应该还是比较熟悉的，有用过CSR的两款芯片，对整体情况掌握度还是比较好，能说出其层次和功能模块划分。
+ 接着聊了一下所做的其他工作，比如系统启动优化，其称之前有把linux的启动从3－4秒左右优化到500ms左右，从其表述来看，对相关知识还是掌握到位的。
+ 对Linux相关知识掌握得还是不错的，对文件系统也有较好的了解。有举例说明其查过一个yaffs文件系统代码下的一个原生bug，并快速定位到。
+ 对QT，uboot，bootloader等均有涉足了解。
+ 有做过部分管理相关的工作，有下属10人左右。
+ 一个项目大概是10几个人就可以完成， 遇到设计相关问题都是大家讨论解决。
+ 项目中会留出编写设计文档时间（这里的设计文档，很多就是类似我们的分析文档， 也就是对一个模块或开源软件的学习和分析的文档），
+ 会进行代码review， 代码review使用reviewboard软件搭建， review时也是整个项目的人员一起参加，通过开会的方式来实现。
+ 总的来说， 这两部分工作对人员的成长帮助很大。
     一个项目会做2年左右， 一般一个产品可以卖5年左右。
+ 已经结婚， 小孩1岁多的样子， 老婆是广州事业单位的，
+ 比较关注后续的职业发展， 对魅族的薪水比较了解（有3个之前的下属在魅族）。 如果去魅族的话， 可以确定提供比16K更高的薪水。

【总体评价】
技术能力不错，知识面了解也比较广，表达能力也比较好。对Linux内核和蓝牙、usb等均有较好的了解，是我们所需要的人才。
目前薪资待遇要求比较高，开价16K以上，不知是否谈得下来。

** 炬芯工作绩效

*** 2014
+ GS705A
熟悉显示子系统的工作流程和工作方法
协助完善DE driver以及显示子系统的软件框架
协助解决系统测试过程中遇到的和显示有关的issue"

+ GS900A
负责显示子系统以及ADF框架的移植和开发
负责HDMI、EDP、MIPI等显示设备驱动的开发和维护
负责送显流程的集成和维护"

*** 2015
+ GS900A
完成显示驱动的基本工作，能满足不同类型项目的需求；
bug数量可控，新出现bug时可以快速定位、快速解决；
完成部分框架整理、软件优化有关的工作。"
+ GS705A
 协助澄清、解决测试过程中出现的显示有关的bug。
+ GL5211 FPGA验证
 在GL5211 FPGA上验证DE、LCD等模块的基本功能。
+ GS900A/AD900B
 完成显示框架的整理和重构
+ GL5211 FPGA验证
 完成。
+ AD700A/GS700D
 基于AD900B，完成第一轮的集成。
+ GL5212 FPGA验证
 基于GL5211 FPGA
*** 2016
+ US282F
负责蓝牙驱动、蓝牙协议栈、蓝牙service的开发和维护，完成开发工作，正在进行系统测试。
+ BLE预研
负责BLE协议栈的前期预研、测试与验证等工作
+ GS700D
显示框架优化、bug fix等
+ GL5116
为US282A、US282C等项目增加微信硬件等功能，已完成。
+ AD900B
bug fix，性能优化，已完成。
*** 2017
+ GL5601
串口相关协议的FPGA验证
+ US282f
负责蓝牙驱动、蓝牙协议栈、蓝牙service的开发和维护，解决系统测试中的问题。
+ zs3503a
百度语音和TTS测试
蓝牙controller功能移植
声波配对功能开发
AirSync功能
** 整体评价
+ 能力很强， 分配的任务都能快速的完成， 在完成的过程中，会发挥自己的主观能动性，自己找到合适的解决方案。会较好的权衡解决方案的利弊
+ 知识面也算比较全面，对小系统， 蓝牙，linux系统都有比较多的涉猎。
+ 工作质量完成比较高，多显示设备相关重构，以及DE驱动的重写完成的质量都很高。
+ 学习新知识很快， 切换工作任务也可以很快上手。
+ 沟通方便也不错， 有自己想法和好的建议都会保持沟通。
+ 性格方面，相对还算比较活泛一些的， 与同事相处融洽
+ 目前看稳定性风险不大， 可能后续到小孩上学时，有可能有变动可能， 之前有聊过可能想在广州上学。不过目前他在广州的房子也卖掉了，在珠海买了房。
** 后续发展
找合适的机会，去承担一个项目的TL的角色，发挥更大的作用，往高级工程师方向发展。
* 李钊军
** 基本情况
出生日期： 1982
入职日期 2014/7/30
毕业时间：2006.7
毕业学校：西安电子科技大学
最高学历：学士
所学专业：通信工程
家里有几口人：5个（父母，配偶，一个小孩）
房子买在梅华西路823号桂香苑
妻子是做外贸的业务助理
父母在珠海帮忙带小孩， 小孩上幼儿园。 有一个姐姐，是文园中学的老师， 父母同时也在带姐姐家的小孩。
** 毕业后工作经历
*** 京信通信（2011.3－2014.6）
嵌入式软件工程师，组长，负责平台开发、维护，小组管理。
工作经验：
+ 作为组长，安排组员的工作，跟进工作进度，对组员的工作成果进行考核，指导、培养组员的专业技能，对新入职员工设计培训计划，指导新员工按计划学习工作需要的技能，举行过多次专业技术培训课程。
+ 接手基于Linux的EP73平台工作，对根文件系统和驱动进行裁剪、优化及版本化管理，在该平台应用于多个项目的过程中，负责硬件的调试，解决出现的相关问题。
+ 全新的EP75平台建设，基于Linux内核，负责完成uboot、内核、根文件系统、用户文件系统及驱动的裁剪、修改、调试，完成各种对外接口的调试。设计Flash的保护及软件可靠升级方案并实现，编写了各部分软件的版本输出管理办法并实施执行。编写通用应用层测试代码，提供方便快捷的调试方式，协助应用业务层完成上下层接口调试，解决产品化过程中出现的问题，最终在产品项目中推广应用。
+ 负责CPLD的平台化工作，定下各种使用规则，使用注意事项，各专业间的交互文档模板。编写了《模块说明文档》，《寄存器使用规范文档》，《测试用例文档》，《寄存器说明文档模板》，《硬件与CPLD交互文档模板》，《自检互检文档模板》，《CPLD需求文档模板》。并在项目中推广应用开来，在各专业交互及软件质量方面取得良好效果。
+       负责从零开始基于SOPC技术在FPGA上搭建NiosII软核，搭建软核过程中，引入和编写个别IP核，在软核上搭建了基于UC_OS操作系统的软件，调通软核内部及对外接口，编写可靠的升级设计方案并实现，解决出现的各种难题，最终实现在多个产品项目中的应用。为了规范软核的设计，编写了《NiosII软核设计规范文档》
+       从引入基于contexM4内核的K22芯片开始，负责K22芯片外部电路的原理图设计，MQX操作系统的clone，完成芯片的启动功能及对外通信接口的调试。编写boot设计方案并实现，完成代码的保护及升级功能。完成应用层操作接口调试，解决芯片硬件相关的各种问题，实现了平台的产品化，最后指导新员工编写K22原理图设计规范。
*** 安凯（广州）微电子技术有限公司（2008.11－2011.2）
软件驱动工程师，负责驱动的开发，调试，维护。
工作经验：
+ 嵌入式软件平台的开发及基于该平台的产品开发（主要涉及驱动的开发）。基于ARM9的芯片开发一套手机软件平台，从调试充电、背光、串口、蓝牙、触摸屏、键盘、WIFI、GPS、LCD开始，到涉及Bootloader、Flash、SDRAM等，对一个手机平台所用到的硬件及软件都有所了解。接着在该平台上开发出了几款产品，其中有一两款产品还在市场有一定的影响（涉及到别的问题，在这不列举所做的产品）。在整个开发过程中，一直作为团队的主力，并且负责过一款产品的开发。
+ 基于Linux系统，整合音视频，移植Minigui，为客户提供一个可以进行二次开发的平台。
*** 宇龙计算机通信科技（深圳）有限公司（2006.7－2008.10）
软件驱动工程师，负责手机驱动软件的开发、调试及测试。
工作经验：
+ 以主力的身份做一套监控软件，基于三菱的一款高级单片机，通过LCD及键盘来控制一台通信设备,并通过一个通信模块以短信或语音数据的形式实现跟后台的互联，由后台可实现对通信设备的监控；
+ 参与做一个通信模块的项目，负责实现了通信模块的AT命令集及对SIM卡的操作两部分，完成了模块对外接口的通信及对短信和通信录的管理(基于嵌入式系统的开发，以UC_OS2为操作系统)；
+ 参与了一款智能手机的开发，负责手机的驱动软件，完成LCD、触摸屏、闹铃、充电、音频等各个模块的功能，为上层各种功能的实现提供了基础(基于嵌入式系统的开发，以UNIX为基础的操作系统)。

** 面试情况
【一面评价（阮勇）】
+ 原来在京信通信工作，6月份已经离职。此份工作3年3个月。之前在安凯工作2年多一点，离职原因是所工作的手机方案部门解散，预计属于解散以后解雇，因为一般公司也会保留一部分人。2006年毕业以后在宇龙工作。
+ 户口深圳。想到珠海定居。原因一是考虑生活舒适一些，环境好；另外其表示有一个姐姐在文园中学当老师，住葵竹苑。姐夫在小学任教。目前住在姐姐家中。配偶在广州上班，销售跟单，表示会在自己确定共作以后过来珠海发展。有一女儿，两岁。小孩目前在老家茂名那边，有奶奶带。 家里兄弟姐妹四个，最大是当教师的姐姐，下有一妹一弟。
+ 性格相对内向，但沟通还可以。描述和解决问题思路还是比较清楚的，有点急于回答问题。对从事过的工作内容细节描述来看，对相关流程还是比较了解的。做过linux的uboot裁剪、linux内核裁剪，有一定经验。目前负责驱动和平台（指系统）
+ 个性相对安静。

【二面评价（侯景昆）】
+ 先后在宇龙、安凯、京信干过，安凯是因为手机部门解散，所以才离开。目前因为家庭原因，希望举家搬到珠海
+ 和肖勇军是同事，从肖勇军处间接也了解到此人技术水平还是不错的；
+ 聊了一下在京信开发的平台的架构和设计情况，主要是从事一个转发基站的新系统升级开发，对各个模块的功能作用还是比较熟悉的，知识面也还比较广。介绍时可能由于紧张，笔绘架构图描述时有些不是很清晰。
+聊了一下启动相关情况，有做过对uboot的裁剪，对启动的整个流程还是比较清楚的。
+ 聊了一下文件系统，有一定的掌握度。
+ 有实现网络设备驱动的经验，知道网络驱动的实现步骤，但对内核网络协议栈的实现过程不太熟悉；
+ 有在windows mobile系统下实现wifi驱动的经验，知道相对以太网，wifi有有些比如ap扫描，身份验证等工作，但具体代码因为厂家只提供dll文件，所以看不到；
+ 本科毕业于西电，工作八年；

  总的来说还是不错的，技术积累比较好，人也还踏实，因此通过二面。

** 炬芯工作绩效

*** 2014
+ RTL8189ETV+8761ATL COB兼容性测试及GS702C无线模组报告整理
+ GS705A上移植rtl8188etv模组,模组切换编译功能		移植完成，测试进行中，存在一些问题，在查问题、解决问题中；模组切换编译功能已完成
+ 通文达_7021+8723AS VAU_调试 Q88		板子带起，模组各个功能调试，还存在一些几率性bug，在调试中
*** 2015
+ GS702C
rtl8723vau模组应用及问题解决
完成rtl8723vau的量产使用，解决存在的问题；
完成rtl8723as-vt调试，问题解决、量产使用；
完成rtl8723as-cg接手，问题解决、量产使用；
各个平台的wifi、蓝牙问题处理，客户问题的解决；
自适应修改，问题解决；
+ GS705A
负责rtl8188rtv、ap6330模组及解决蓝牙存在问题
完成rtl8188etv模组的移植、调试、内测、问题解决；
ap6330的问题解决；
解决GS705A项目中出现的蓝牙问题；
完成bubblegum项目的模组自适应需求；
rtl8189ftv调试、测试；
客户板子上调试rtl8703bs；
+ GS900A
负责AP6330模组及浅睡眠调试
完成ap6330模组的移植、调试、内测；
调试wifi浅睡眠功能并协助其它模组的调试；
文档编写
完成wifi driver层级硬件的总结文档；
完成Android平台bluetooth应用层软件总结；"
+ AD500A
ubuntu、debian下rtl8723bs模组的wifi、蓝牙调试
文档编写及培训
完成wifi driver层级硬件的总结文档及培训；
 完成Android平台bluetooth文档编写、整理、培训；
 完成ubuntu平台bluetooth文档编写、整理、培训；
*** 2016
+ GS705B
完成要求的wifi、蓝牙模组、cob的调试；
解决客户遇到的wifi、蓝牙问题；
协助深圳调试wifi、蓝牙问题；
android 6.0上wifi、蓝牙调试；"
+ GS700E
解决VR上wifi、蓝牙相关问题；
新增加模组的调试、兼容；
蓝牙pcm通话功能调试；"
+ GL5119
完成ivt代码裁剪评估；
ivt代码的裁剪，完成30%"
+ GS700D
完成通过vendor id实现多模组支持；
解决wifi、蓝牙相关问题；
+ AD500A、GS500B
解决客户wifi、蓝牙相关问题；
新增加模组的调试、兼容；
+ AD900B、GS900C
解决wifi、蓝牙相关问题；
+ 开源及差异化项目
解决客户wifi、蓝牙相关问题；
协助深圳分析、调试wifi、蓝牙相关问题；"
*** 2017
+ zs350a
 和SSl合作wifi驱动开发和维护
zephyr协议栈开发和维护
http协议和mqtt协议开发
jason编码库开发
+ LS370A
linux 功能WIFI功能开发和一直
+ AD700A
蓝牙做slave功能
+ 维护项目
WIFI和蓝牙相关问题解决
** 总体评价
+ 工作非常踏实， 对安排的工作都能很好的完成， 2016年，安排了5119的蓝牙协议栈压缩代码的工作，也都认认真真完成了。 2017年开始又开始在3503项目wifi和网络协议栈上的工作，都完成得较好。
+ 工作很努力， 任劳任怨。即使是不是特别紧急的工作，也会加班来完成。在做3503工作的时候，还尽量的完成了不少android平台的支持工作， 以及LS370A上的WIFI的支持工作。
+ 工作能力方面，在WIFI和BT方便都有较好的积累， 特别是WIFI方面，逐渐具备深入的专业知识，遇到的网络相关的问题，都能够有效解决。
+ 学习能力和潜力方面， 不算特别突出， 不是能够非常快速学习新知识的， 但能够沉下心来， 把一个复杂的专业领域深入的掌握，这一点也是很好的品质。 有主动学习的意愿和行动，在工作安排没那么多的时候，会主动的去学习和掌握需要的专业知识。
+ 目前尚未表现出具备有很好的架构能力的潜质， 这一点跟工作安排也相关，也未安排合适的这部分任务给他 。
+ 个性比较安静，能够沉下心来专心做技术，也没有沟通方面的问题
+ 应该不是喜欢冒险的人员， 在薪水，前景，工作安排不出大问题的情况下应该会比较稳定。
+ 目前薪水偏低，需要及时做一次调整。

** 后续发展路线
继续成为WIFI和蓝牙方面的资深专家， 有合适机会的话，补充系统架构方面的知识
* 刘燚光
** 基本情况
2009年毕业于广东工业大学，本科，电子科学与技术。
入职日期 2014/8/11
家里暂时5口人，在坦洲香格里拉买有房子，已经有一个小孩上幼儿园，配偶待产，母亲退休带小孩。
妻子在坦洲一家公司上班
上班主要依靠公司班车
** 毕业后工作经历
珠海安联锐视科技有限公司（3年）；深圳福斯康姆科技有限公司（2年）。
主要负责安防监控产品嵌入式端的应用、驱动开发工作。

2012/12-至今	深圳市福斯康姆（FOSCAM）集团	嵌入式软件工程师
职责业绩：	公司介绍：是一家专注于研发、设计、制造及销售网络摄像机、网络视频录像机、网络音视频存储、光学模组等产品的国家级高新技术企业。安防监控公司，主打自己的品牌。产品主要有IP Camera(IPC)和Network Video Record(NVR)。产品属于纯IP类。
工作职责：
1.负责嵌入式软件底层开发(在ARM Cortex平台下，包括Uboot，Linux Kernel，Rootfs)，设计工作，软硬件联调和对接工作，硬件驱动开发工作。
2.负责嵌入式软件需求分析和参与各大模块的设计工作。
3.负责整个工程项目的Makefile编写。
4. 负责网络接口程序开发，网络协议制定工作。
5.负责视频解码及与解码相关的应用程序开发工作。
6.负责协调整个项目的开发进度及汇总工作。
工作业绩：
在一年的时间里，四人团队，从无到有的开发并完成NVR项目。在2013年第二季度被评为公司优秀员工，研发部共40人仅两人入选。目前，该项目已经进入试产和量产阶段。

2009/11-2012/12	珠海安联锐视科技股份有限公司	嵌入式软件工程师
工作职责：
1.参与老产品源程序维护及修改、客户功能需求的定制和版本问题跟踪。
2.参与产品用户界面设计，自主设计及客户定制。
3.参与底层驱动及接口协议的开发。
4.参与新产品的研发，主要工作包括参数架构，音视频存储、传输及其他相关的应用程序。
5.参与视频编解码，硬件驱动等开发工作。
工作业绩：
三年海思Hi35xx系列(ARM内核)数字硬盘录像机(DVR)的嵌入式软件研发经验。其中，一年以上IP Camera和NVR研发经验。
三年期间为公司90%的OEM客户定制过DVR固件；
为公司新产品IP Camera和NVR的研发先行者，目前这两款产品已上市。
** 面试情况
一面（通过）：吴瑞
1）刚在坦洲买了房子，而目前工作在深圳，生活工作不方便，想回到珠海工作。
2）近几年来都在做网络摄录像相关的工作，对camera和linux应用层的网络通信有相当的了解。
3）问了移植平台相关的工作，对u-boot的移植启动过程有相当的了解，但对linux怎么启动到shell的过程不了解。
4）问了linux下串口驱动的实现，了解较多。
5）对android没什么了解。
6）认可加班，其目前公司的加班是工作日加班到9：00，周末加班一天。
总结：对u-boot有相当的了解，但对linux kernel和android了解不多，对linux应用较为了解，对linux驱动了解一些

二面(通过)：王艳武：
1)	进一步了解了求职动机，以及薪资方面的需求
2)	询问了camera项目中视频流的搜集，音视频的协同处理，以及同步等问题，回答可以。
3)	对linux系统了解不是非常深入
4)	观察其谈吐，以及回答问题来看，此人的做事比较稳健，性格比较平和。
总结：可以考虑招录

** 炬芯工作业绩

*** 2014
+预研
  Camera Hal 3.2开发预演/评估
  初步总结Camera Hal 3.2的调用流程及接口，组内发起讨论。
+ GS705A
  Android L Camera Hal 1.0移植
  把Camera Hal 1.0从Android 4.4.4移植到Android L环境中，
  把Camera2.apk的已有的功能全部验证和测试。修改原有的Hal 1.0，使之可以通过Android L的cts和cts verifier测试。Android L首发样机Camera相关功能支撑。
  优化启动流程，缩短量产后第一次打开Camera到取景器所需要的时间；
+ GS900A
  Android L Camera Hal 1.0移植和联调
  在GS900A的环境中移植和联调Camera Hal 1.0。
  联调主要内容是64位兼容支持和对接新的YUV和Raw Sensor、添加更多的分辨率支持等。
  CES展示样机Camera相关功能支撑。
*** 2015
+ Camera Hal 1.0兼容性移植
  使Camera Hal 1.0能兼容GS705A/GS900A标案项目，且兼容64位编译。
+ Camera相关新功能流程添加及联调支持
  包括：闪光灯、HDR、对焦等。
+ Camera已有功能优化
  包括：VCE硬编码调用优化；
  Camera最佳预览、拍照分辨率选择；
  Camera Frame格式转换流程修改；
  从效率和效果上对Camera相关功能进行了优化。
+ Camera问题跟进及解决
  包括：CQ、CTS及Camera相关的Mokey测试问题跟踪及解决。
+ Hal 3.2调研及开发
  调研了Hal 3.2实现的必要性以及主要接口进行了描述。功能开发方面，目前仅实现了预览功能。
+ SI和ISP驱动整合
  对原有S700和S900驱动的框架进行改动，使驱动模块的程序可同时兼容SI和ISP，方便以后维护和管理。
+ CVR项目预演
  在中间件里联调实现移动侦测和水印功能。对该项目Camera模块相关功能提供必要的支持。
+ Camera问题跟进及解决
  涉及项目：900A、900B、GT9、S700、S900、GT7。涉及模块：Camera Hal、UVC驱动、Sensor驱动等。问题包括：CQ、CTS及Camera相关的Mokey测试问题跟踪及解决
*** 2016
+ Camera功能开发及维护
  涉及项目：S500、S700、S900以及就旧项目ATM7051/ATM7059、LS370等；
  涉及模块：Camera Hal、Camera Sensor驱动、UVC驱动及Camera应用等；
  完成的功能包括：HDMI IN模拟成Camera Sensor输入、Usb Camera功能支持、双Camera同时使用支持，Camera新模组驱动支持，Camera测试问题跟进及客户功能支持等。
+ GT7 MboxLauncher应用维护
  M8S盒子方案Launcher定制和维护，测试问题跟进。
+ 陀螺仪功能开发及维护
  涉及项目：S500、S700、S900平台下的VR方案的陀螺仪功能。
  支持了陀螺仪+地磁的组合有：icm20602+ak0991+ mpu6500+ak896+ mpu6500+ak09911，完成了这些组合的Hal和驱动的调试并对接了Android的SensorService。
+ 光感功能开发及维护
  在S700平台下的VR方案实现了光感stk3311的功能支持。
*** 2017
+ V700
  光感和陀螺仪以及地磁问题跟进
+ S900
  HDMI IN功能调试
+ LS370A
  camear功能开发，包含应用框架以及camera
  camera效果调试
  趣味拍照功能开发
  卡拉OK录像功能
  人脸识别和sayHello规格，整合地平线相应功能
** 总体评价
+ 能力不错， 在camera相关方面有多年的工作积累，andorid平台的camera hal和camera驱动都能一个人完全负责，并负责多个平台的相关工作。LS370A的camera相关工作都是重新开发的，包括和地平线联调，camera应用，工作内容相对较多，也能较好的完成
+ 转换工作方向也能较快的掌握，在vr项目中做陀螺仪，光感地磁等都能较快的接手并完成任务
+ 在工作任务需要的时候也会主动的加班来干进度， 尽管上下班不是太方便
+ 个性比较沉稳，不浮躁。
+ 自己工作范围内的事情会比较好的完成， 但主动去学习其他关联模块的主动性不足
** 后续技术发展
在完成本职工作后，需要接手nandflash驱动，以及开始熟悉升级量产，补充系统方面的知识，承担更多的任务。
* 刘新旭
** 基本情况
+ 学业情况；
2010年毕业于中南民族大学，本科，计算机科学与技术专业
+ 家庭情况；
一家八口人，兄弟一家在西安；
老婆做测试行业，在优特电力。老婆本来是重庆人，去年有计划要去重庆分公司的。
目前住金湾区， 是购买的房子，小孩不满周岁，目前开车上下班，途中需要1个小时左右。
+ 毕业后的工作情况；
2010年到2014年10月份在珠海迈科智能科技，第一个阶段STB数字机顶盒相关；第二极端，OTT+DVB相关；
2014年至今在珠海炬芯；

** 毕业后的工作经历
2010/7-至今	珠海迈科科技	高级软件工程师
职责业绩：	公司简介：全球专业的数字电视终端接收设备ODM/OEM制造商。致力于全球中高端数字电视机顶盒、数字液晶电视等整机的研发、生产与销售，专注于3D技术、数字电视加密解密系统、数字电视视频传输、数字电视测试检测设备、网络信息安全、安防系统、内容服务系统等的研发。
汇报上级：部门经理
下属人员：5人
工作职责与业绩：
+ eCos平台(主要开发人员)
主要职责：DVB数字信号频谱调试，外围IC调试以及其他应用的开发与维护；
+ Linux平台
基于Enigma2系统的DVB系统开发(主要开发人员)
   主要职责：主要负责整体代码把关；DVB相关应用开发；3G模块驱动移植，以及应用配置等；wifi模块驱动移植，应用配置及其他；
安卓系统(项目组长)
   OTT项目：主要负责前期项目准备，项目计划的制定以及任务的分配；参与安卓的系统定制开发；参与与其他聚合平台对接；安卓应用的开发；
   DVB项目：前期项目准备以及计划制定；前端IIC设备驱动移植与调试；中间DVB Stack部分的开发，以及UI层的维护与开发。

** 面试情况
一面（通过）：王艳武
1）目前公司是做机顶盒相关产品的，软件总人数200多人，老婆在u特电力，想搬到市区。
2）问了一下当前负责的工作内容，让其描述一下开发一个产品他们自己都要做哪些开发，然后简要介绍了一下移植流程，回答比较清晰
3）询问其项目中的一个后台服务与前台交互的流程，对其中一些异常如何处理，例如客户端异常退出等，回答尚可。然后就是问了一下android四大组件的一些基础知识，知道一些，回答一般。
4）我总体介绍了一下炬力当前的产品，以及盈利模式，产品开发中的重要软件模块，android软件工程师职位的相关工作内容。
5) 薪资要求是13k左右。

一面通过: 王艳武
总结：基础知识尚可，回答思路清晰，可以考虑招聘进来负责android应用层的开发。

二面：张东风
1）公司主要是做机顶盒的， 有dtv和ott的，  分别是ali和全志的平台， 对产品表述比较清楚
2）anroid部分从5月份开始接触， 对android的framework有一些了解，
其中问道实现如何限制浏览器访问网络， 通过开发后台服务来控制iptable， 以及修改packagemanager限制浏览器类的应用安装，
3）目前带了5个人左右， 负责两个项目， dtv和ott的各一个。
平时加班比较多，有时会加班到2~3点，  周末一般不加班。
4）目前在公司应该还比较受重用， 这次有换工作的想法， 主要从两方面考虑，
个人的发展，以及薪水也可以有一定幅度的成长。
5）沟通和表达能力不错， 表述比较有条理和逻辑。
6） 应该是一个比较踏实努力， 能够深入做事情的人。
7）主要向我们了解了成长路线， 技术职和管理职的问题。
8）目前工作4年， 薪水大概10K的样子， 期望13K， 能接受12K的薪水。

综合而言， 二面可以招入， 薪水的话， 考虑到和内部倒挂， 给12K比较合适一些。


** 炬芯工作绩效

*** 2015
+ GS705A/GS900A项目研发
  Android平台维护
+ GS705A/GS900A项目研发
  第三方APK兼容性调试
+ GS705A/GS900A项目研发
  平台显示类问题的澄清
+ GL5211 FPGA验证
  Mali GPU验证
+ GL5211 FPGA验证
  Mali GPU驱动的开发与维护
+ GL5211
  Mali GPU驱动以及相关模块的开发与维护；
  Mali GPU 功能验证
+ GS705A
  平台显示类问题的澄清；+ 第三方APK兼容性调试；+ Android平台维护
+ GS900A
  平台显示类问题的澄清；+ 第三方APK兼容性调试；+ Android平台维护
*** 2016
+ GS700D
  完成GPU驱动部分一些feature的修复以及优化、性能分析、功耗澄清、调频策略支持等；
  HWC部分完成对于HDMI+CVBS双显的支持、新功能的添加、以及部分BUG的修复；
  Gralloc模块问题的修复；
  skia中间件的问题修复；
  MediaProvider问题修复
+ GS700E
  完成两种分屏机制的添加；
  GPU DVFS框架的优化，优化各个场景功耗问题；
  UI帧率、游戏帧率、以及视频播放帧率等性能相关的澄清以及优化；
  修复DE部分的BUG；
  澄清skia模块相关bug；
  修复MediaProvider模相关BUG；
  协助完成QC测试部分GPU的Pattern的制作；
  完成对于VR方案HDMI+LCD双显方案的支持；
+ GS705B2
  完成skia的合并与测试验证、
  Mediaprovider合并移植，
  以及一些其他对于Android M的合并
+ LS370A
  完成图片解码部分中间件移植、系统UI组件；
+ GL5212
  完成GPU硬解带起Android显示、FPGA验证、跑Pattern验证；
+ 其他：
  包含900C、705A、500B项目的skia和媒体扫描的支持；
*** 2017
+ LS370A
GUI 显示框架开发
photo应用开发
媒体扫描开发
WIFI应用开发
ota应用开发
+ AD700A
维护工作

** 综合评价
+ 工作能力不错，mali GPU是我们第一次使用，之前并没有经验积累，在较短的时间内，能够熟悉起来，并完成FPGA验证，同时也在验证中有效的发现了一些问题，并解决了。 起到了很好的效果。在方案开发阶段也能较独立的完成GPU相关的工作。
+ 可以胜任多种不同性质的工作内容， 在LS3703A中，也能很快的上手，负责了较多的开发人物，完成工作的效率，和debug的效率都不错，工作质量较高， 对负责的模块还是有精益求精的要求。
+ 2106工作量不是特别饱满，一部分原因是工作安排原因，一部分是要去重庆的原因
+ 工作认真负责， 任务较多时，会自己加班完成，
+ 性格比较稳重，对工作和生活都有一定的目标性， 前一份工作做了4年， 在待遇和个人发展没有出现太大状况，或者外部环境不发生太大变化的情况下，应该有一定的稳定性。
** 后续发展
在继续维护现有模块的情况下， 开始学习和接手LS370A的WIFI和以及android系统的WIFI和BT维护。
在上层掌握到一定程度后， 适当往底层发展。
* 吕锦昂
** 基本情况
+ 学业情况
毕业时间：2015-07-01
毕业学校：湖南大学
最高学历：大学本科
专业：自动化
+ 家庭情况
老家在浙江东阳市，未婚，女朋友是质量部的杨丹
+ 工作情况
毕业至今：炬芯（珠海）科技；
工作内容：linux usb模块维护和开发
** 拓展评价
团队角色测试-个人报告
你在团队角色首要倾向为：外交家 RI（Resource Investigator）
A 典型特征: 性格外向；开朗；热情；好奇心强；联系广泛；消息灵通，是信息的敏感者。
B 积极特性:有广泛联系人的能力；不断探索新的事物；勇于迎接新的挑战
C 弱点: 事过境迁，见异思迁，兴趣马上转移
D 在团队中的作用
提出建议，并引入外部信息（一个很好的比喻是：RI 对于团队的作用，就像天线对于电视机，RI 就是团队的天线，就是用来接受外界信号的。注意RI和PL的区别：PL的想法大都是原创自己想的，RI则更可能是他个性喜欢接受新鲜事物，因此 RI 更擅长整合外界新鲜信息。）
接触持有其他观点的个体或群体
参加磋商性质的活动

你在团队角色次要倾向为：完美主义者 FI（Completer Finisher）
A 典型特征: 勤奋有序；认真；有紧迫感
B 积极特性: 理想主义者；追求完美；持之以恒
C 弱点: 常常拘泥于细节；焦虑感（注意和SH的不同，SH有紧迫感，但FI是焦虑感）；不洒脱
D 在团队中的作
强调任务的目标要求和活动日程表
在方案中寻找并指出错误、遗漏和被忽视的内容
刺激其他人参加活动，并促使团队成员产生时间紧迫的感觉
** 炬芯工作绩效
*** 2015
+ AD900B
  学习USB和Linux驱动基础知识。
  调试uboot USB，device功能：ums,fastboot,rndis；host功能：调通USB中断传输。
  kernel USB host debug。
+ GS700D
  移植AD900B USB相关uboot和kernel的代码。
  USB模块host和device功能验证，uas代码同步和性能对比测试。
  内测debug：camera相关音视频bug和uhost兼容性问题分析和处理。
*** 2016
+ GS700E
  u-boot adfu模块实现与维护；
  Linux USB3.0 模块维护；
  Linux USB aotg模块学习和维护；
  android adb/vold/mtp维护。
+ GS900C
  u-boot adfu模块实现与维护
  Linux USB3.0 模块维护；
  Linux USB aotg模块学习和维护；
  android adb/vold/mtp维护。
+ GS500B
  linux USB3.0/USB2.0问题同步和维护。
+ 平板其他项目
  android 7.0 vold和monitor同步；
  kernel 4.4 adfu同步；
  GS705B USB eth等维护；
+ 多媒体其他项目
  GL5009G USB debug；
  GL5009G USB移植；
*** 2017
+ LS370A
USB驱动开发
USB上层应用开发
+ ZS3503
USB HOST支持。
USB读卡器开发
+ 平板以及其他方案
相关USB模块维护
** 总体评价
+ 从工作能力上看，现在已经能够独立的完成usb模块的开发维护和debug工作。 具备维护和开发andriod， linux， ucos，以及zephyr等各个平台的usb驱动。
+ 作为2015年的应届毕业生， usb模块相对还是比较复杂一些的模块， 能够较快的掌握和独立解决问题， 成长很快。
+ 工作效率也不错
+ 工作努力踏实， 由于工作安排较多，几乎天都加班到9点钟以后，周六也有加班
+ 学习能力是比较突出的，在有限的时间内还是比较快速的掌握usb相关的知识，同时在切换不同的系统平台的时候，也能够很快适应， 表现出不错的学习能力。
+ 个性也相对安静，与同事相处融洽，私下肯定也有比较有激情的一面，他女朋友是来公司后才处的。
** 后续发展规划
需要继续负责各个平台USB相关的工作，有余力的时候，继续在底层驱动方面发展一点时间， 掌握更多的驱动模块
* 蒋斌
学业情况：
2012 湖南工程学院，本科、计算机科学与技术；
目前已经在珠海海怡湾畔买房
妻子是测试工程师测试工程师
有房贷和车贷要还
3 .     毕业后的工作情况，迈科智能，炬芯，嵌入式开发，android
** 毕业后工作情况
2013.01-至今                  Mstar6369
项目职务：系统集成开发
项目描述：中高端智能电视平台，开发交互 apk，定制特色服务，移植最新的 device，适应目前最新潮流功能。
项目职责：apk 的优化 debug， framework 中间层定制以及底层优化和驱动的移植。
项目业绩：
1.添加系统客户化编译体系: (android 系统编译体系定制，客户化签名系统 key，机制贯通整个系统)；
2.添加移植 3G 模块驱动: (linux 内核中的兼容配置， android 层 RIL 通信驱动层相关配备添加，实现数据流量
访问 Internet)；
3.划分配置 emmc flash 分区： (配置划分 android 磁盘存储，修改定制系统 VOLD 挂载机制，内外 sdcard 挂载)；
4.移植红外触摸框设备驱动: (配置 linux 模块驱动， android 中 input 子系统框架)；
5.GPIO 模拟 NEC 红外： (linux 中 gpio 口模拟 nec 协议的红外发送驱动编写linux driver->HAL->JNI->service-aidl-binder->app)；
6.OTA 网络升级： (android OTA 刷机机制，网络在线更新解决方案)。


** 面试情况
一面（通过）：王艳武
1）目前在珠海工作，换工作的原因主要是： 当前公司（迈科）智能电视项目组，暂时没有上量可能，而且前景不明朗，所以想换一份工作
2）之前工作包括：mstart智能电视方案中部分android framework的修改，apk的debug及分析；看得出来做过一些事情，对做过的事情表述清楚，但不是非常深入
3） 技术方面：问过负责的几个模块：TvManagerService的实现，启动，编译机制；android build，签名机制；以及vold磁盘挂载等，回答尚可，但算不上非常精通。
4）基础知识方面：毕业学校一般，对于os/计算机组成掌握较差，对于语言方面，也只是能用。问了几个c++的问题，回答不好，但是思路是清晰的，回答也比较诚恳。
5) 已经面试过全志，对方开出的薪资结果为10k * ( 12+3), 公积金按照10%购买，女朋友在金山做测试，准备结婚。

总结：
目前能力还算可以，经历过的项目与我们当前的相似度较高，估计上手会快一些；基础只是比较欠缺，尤其是c++语言类，以及os类的基础；建议招录进来，负责android framework中部分模块的研发。

二面（通过）: 张东风
时间较短问了两个技术问题：
gpio模拟红外的时序应该怎么保证时序是正常的， 考虑到linux有终端好调度的影响， 谈到使用优先级或限制资源的办法， 回答不是很切题， 问是否了解过linux，基本上么有太多了解。
也问了vold的识别3G dongle的完整过程那个，大致流程都清楚，也知道改哪些地方，但对设计到的比如device节点创建， ueventd等内容不是很清楚， 要提醒后次想起来有这回事。
总的来说， 专业知识比较对口， linux部分知识叫薄弱， 工作经历比较契合， 发展潜力不是很大， 但可以胜任一般复杂度的工作，
人比较直接和爽快， 谈待遇的时候可以看出这点，较踏实和努力。
薪水11k， 建议录用。
** 炬芯工作绩效
*** 2015
+ GS705A
  readahead自动机制,coredump添加分析，跑分
+ AD500A
  airplay性能优化,性能分析澄清
+ AD900B
  DEBUG，跑分以及相关性能分析
+ AD900B_VR
  研究unity的使用开发，分析调试VR场景
*** 2016
+ GS705B
  debug以及性能分析澄清
+ GS700D
  Kodi的开发调试
+ AD500A，GS900C
  OpenCL，OpenCV的移植开发，调试相关优化性能
+ S900_VR
  google cardboard-daydream平台的研究使用
+ VR-FBO-ATW
  单buffer显示，SF中根据sensor送显前的ATW应用
+ FACE-SPEECH
  人脸识别相关学习，基于OpenCV的人脸检测与识别
  了解语音识别，搭建运行kaldi平台用例
*** 2017
+ GS900C
google daydream预研，成功在S900上跑起来了daydream
+ ZS350a
负责播放器的功能开发
播放列表功能开发
mqtt开发
** 综合评价
+ 能力还可以，负责的工作都能较好的完成，
+ 掌握新知识的能力好，工作以来多次切换工作，多次变化工作方向和工作内容， 都能够很快的熟悉并开展工作，表现出了很好的学习能力。
+ 工作努力程度还可以， 在工作饱满的时候也会主动加班完成， 但在工作安排没有那么多的时候，就相对放松一些
+ 主动提高自己的愿望不是很强烈
+ 对薪水和待遇应该较看重，遇到较好的机会的话， 有不稳定的风险。
+ 对应用层知识掌握较好，缺少底层知识
** 后续发展
继续发挥特长，安排更多合适的工作，稳定性问题不大后，考虑往全面性方面发展。

* 黄海宇

** 基本情况
2015年7月12号毕业于西安邮电大学软件工程专业，本科学历。
老家西安，家里还有一个妹妹。
毕业后入职炬芯科技至今，主要负责Android显示模块方面的工作。

** 拓展训练评价
团队角色测试-个人报告
你在团队角色首要倾向为：CW（Company Worker，后来在1988年改称为 Implementer ）
A 典型特征：保守；顺从；务实可靠
B 积极特性：有组织能力、实践经验；工作勤奋；有自我约束力。
C 弱点：缺乏灵活性，应变能力弱；对没有把握的主意不感兴趣。
D 在团队中的作用
把谈话与建议转换为实际步骤。
考虑什么是行得通的，什么是行不通的。
整理建议，使之与已经取得一致意见的计划和已有的系统相配合。
实干家就是好的执行者，能够可靠的执行一个既定的计划，但却未必擅长制定一个新的计划。

你在团队角色次要倾向为：完美主义者 FI（Completer Finisher）
A 典型特征: 勤奋有序；认真；有紧迫感
B 积极特性: 理想主义者；追求完美；持之以恒
C 弱点: 常常拘泥于细节；焦虑感（注意和SH的不同，SH有紧迫感，但FI是焦虑感）；不洒脱
D 在团队中的作用
强调任务的目标要求和活动日程表
在方案中寻找并指出错误、遗漏和被忽视的内容
刺激其他人参加活动，并促使团队成员产生时间紧迫的感觉
** 炬芯绩效

*** 2015
+ AD900B
  mipi-dsi屏支持调试工作、LVDS驱动支持及调试。
+ ATM7059C和ATM7059合并
  mipi-dsi屏调试支持工作
+ AD700A
  SDK级功能验证mipi-dsi驱动支持及屏调试
+ AD900B/AD700A
  mipi-dsi驱动兼容性支持。
+ AD500A
  HDMI-CEC功能支持。
*** 2016
+ GS700E
  显示驱动调试
+ GS900C
2k屏驱动开发， 主要解决夏普， auo等2k屏的闪屏问题。
HDMI功能开发和维护
双屏显示功能
启动和recovery显示维护
+ GS500B
  显示驱动调试
*** 2017
+ GS700E
小辣就 hdmi2dsi
小辣椒显示问题解决
+ LS370A
lcd驱动维护和问题解决
+ GS900c
新的2k屏调试
双1080屏显示
+ AD700A
CVBS IN芯片功能调试。
Recovery双显问题

** 总体评价
+ 工作态度端正， 配合度好，对交待的事情都能很好的配合完成。特别是2k屏的闪屏问题，比较繁琐和磨人，都能认真仔细的做好， 表现出了很好的耐心。
工作努力认真， 需要加班的时候也能很好的配合，在2016年VR项目开发的过程中， 调试屏的时候经常需要深夜几班， 都有很好的配合。
+ 与团队其他成员相处融洽。在别人需要帮助的时候，能提供帮助，需要别人帮助的时候，也会主动去问， 工作基本可以独立锦兴。
+ 在技术方面， 能够胜任LCD调试， HDMI相关功能调试， DE驱动的调试和维护。 能够做相对独立，复杂性不是特别高的模块。 但对整个显示系统的掌握还是不够深入，需要继续努力。
+ 在工作相对有时间的时候，会主动去学习自己工作相关的模块内容，能力逐渐由成长。但学习能力不算特别突出， 速度一般。
+ 个性相对比较安静，能够静下心来。
** 后续发展路线
继续掌握android Linux平台的显示相关的专业技术， 尽快可以独立的负责更多显示方面的工作。
